stages:
  - compile
  - test
  - sast
  - depend-scan
  - deploy

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

compile:
  image: maven:3.8-openjdk-11  
  stage: compile
  script:
    - mvn compile -s ci_settings.xml

test:
  image: maven:3.8-openjdk-11  
  stage: test
  script:
    - mvn test -s ci_settings.xml

sonarqube-check:
  image: maven:3.6.3-jdk-11
  stage: sast
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: '0'
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".sonar/cache"
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=final-exam-a-als0184 -Dsonar.qualitygate.wait=true
  allow_failure: true

deploy:
  image: maven:3.6-jdk-11  
  stage: deploy
  script:
    - mvn deploy -s ci_settings.xml
  only:
    - main  

include: '/templates/Dependency-Scanning.gitlab-ci.yml'
