stages:
  - build
  - test
  - sast

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

login-build1:
  image: maven:3.8-openjdk-11
  stage: build
  script:
    - mvn compile

login-test1:
  image: maven:3.8-openjdk-11
  stage: test
  script:
    - mvn test

sonarqube-check:
  image: maven:3.6.3-jdk-11
  stage: sast
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: '0'
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".sonar/cache"
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=M3A-als0184 -Dsonar.qualitygate.wait=true
  allow_failure: true
